### ISSUE TITLE
Overly strict test + workflows `pull_*()` soft deprecation

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/finetune#22]
Running revdeps for workflows 0.2.3 revealed a failure with finetune.

Specifically, this test fails now because it expects silence
https://github.com/tidymodels/finetune/blob/67658bc0b62dfc7d042c7f67b029eb05193c81e5/tests/testthat/test-anova-filter.R#L131-L141

It is no longer silent with workflows 0.2.3 because somewhere in the tuning process (I think in {tune}) one of the `pull_*()` functions from workflows is called. Since those are soft-deprecated, a warning is thrown when tests are run (but not when used interactively) and that warning causes the test to fail.

I plan to submit to CRAN anyways, and link to this issue noting that we are aware of this and will update tune and finetune to use the new `extract_*()` functions instead

**Comment by simonpcouch** [comment]
This was addressed in https://github.com/tidymodels/tune/pull/388. :)
