### ISSUE TITLE
backend_options missing

### ISSUE THREAD

**Issue by Jeffrothschild** [tidymodels/finetune#56]
Hi, I am now getting the following error when using finetune, which I wasn't getting when I last used it a couple of months ago - "Error in `parsnip::condense_control()`:
! Object of class `control_race` cannot be coerced to object of class `control_grid`.
• The following arguments are missing:
• 'backend_options'

This occurs with my own data, or when copying the examples [here](https://github.com/tidymodels/finetune) or [here](https://finetune.tidymodels.org/reference/tune_race_anova.html#ref-examples)

**Comment by EmilHvitfeldt** [comment]
Hello @Jeffrothschild, I'm not able to reproduce this error with CRAN versions of this package. Can you run the following reprex and let me know what happens?

``` r
library(finetune)
library(parsnip)
library(rsample)
library(dials)
library(discrim)

packageVersion("parsnip")
#> [1] '1.0.2'
packageVersion("tune")
#> [1] '1.0.1'
packageVersion("finetune")
#> [1] '1.0.1'

data(two_class_dat, package = "modeldata")

set.seed(6376)
rs <- bootstraps(two_class_dat, times = 10)

# optimize an regularized discriminant analysis model
rda_spec <-
  discrim_regularized(frac_common_cov = tune(), frac_identity = tune()) %>%
  set_engine("klaR")

ctrl <- control_race(verbose_elim = TRUE)
set.seed(11)
grid_anova <-
  rda_spec %>%
  tune_race_anova(Class ~ ., resamples = rs, grid = 10, control = ctrl)
#> ℹ Racing will maximize the roc_auc metric.
#> ℹ Resamples are analyzed in a random order.
#> ℹ Bootstrap05: All but one parameter combination were eliminated.

# Shows only the fully resampled parameters
show_best(grid_anova, metric = "roc_auc", n = 2)
#> # A tibble: 1 × 8
#>   frac_common_cov frac_identity .metric .estimator  mean     n std_err .config  
#>             <dbl>         <dbl> <chr>   <chr>      <dbl> <int>   <dbl> <chr>    
#> 1          0.0691        0.0437 roc_auc binary     0.886    10 0.00513 Preproce…

plot_race(grid_anova)
```

![](https://i.imgur.com/GAxz7ZR.png)

**Comment by Jeffrothschild** [comment]
Ah, sorry. I was still on finetune 0.2.0. Getting the new version sorted it out, thanks!
