### ISSUE TITLE
[Feature Request] Is it possible to include the genetic algorithm to tune hyper-parameters in Tidymodels?

### ISSUE THREAD

**Issue by Freestyleyang** [tidymodels/finetune#64]
Hi There,

The Genetic Algorithm has been shown to achieve better results compared with the classic grid search for hyper-parameter tuning. It gains the optimal solutions of the objective function by selecting the best or fittest solution alongside the rare and random mutation occurrence. 

I wonder if it is possible to include the Genetic Algorithm for hyper-parameter tuning? I believe this will greatly enhance the performance of machine learning models in tidymodels. Thank you.

Regards,
Yang
#

**Comment by Freestyleyang** [comment]
@hfrick Thank you for your reply! I am loking forward to the future development plan from @topepo.

The genetic algorithm is available from the [R package "GA".](https://cran.r-project.org/web/packages/GA/index.html) 

Some examples on tuning hyper-parameters using the genetic algorithm are available below for your reference. Thanks.
[https://algotech.netlify.app/blog/optimization-with-genetic-algorithm/](url)

[https://towardsdatascience.com/genetic-algorithm-in-r-hyperparameter-tuning-5fc6439d2962](url)

As you will move the topic to the `finetune` repo, can I still have access to my feature request? Thank you.

**Comment by hfrick** [comment]
Yes, you still have access - if you look closely, you can see that it's now an issue on the finetune repo. that's all that happened and you can still see it, comment etc 👍 

Thank you for the references!

**Comment by topepo** [comment]
I don't think that we will implement this. GAs end up fitting _a lot_ of models during tuning. While it is effective, it isn't at all efficient compared to other sequential optimization tools. 

While [this repo](https://github.com/topepo/Optimization-Methods-for-Tuning-Predictive-Models) has code that used the `caret` package, you can adjust it to work with tidymodels. There is also code for Particle Swarm optimization, Simulated annealing, and Nelder-Mead.
