### ISSUE TITLE
Move BradleyTerry2 from Suggests to Imports?

### ISSUE THREAD

**Issue by skeydan** [tidymodels/finetune#8]
Hi,

please close if you disagree, but I wonder if users would appreciate the suggested change ... As-is, when you use `tune_race_win_loss` but don't have that package installed, tuning will fail at the end, and the user will have lost their time ...

**Comment by topepo** [comment]
Sorry; that must have been frustrating. I'll add a check for that package when `tune_race_win_loss()` is first called.
